### ISSUE TITLE
Experimental Results

### ISSUE THREAD

**Issue by flyingdoog** [echo740/DANSER-WWW-19#4]
Dear authors,

I have run the code for 1000 epochs and my experimental result is slightly different from the one reported.
 
Specifically, 
"Epoch 1000 Step 8643000 Train_loss: 1.0127 Test_loss: 1.1674 P@3: 0.9010 P@5: 0.8825 P@10: 0.8244 NDCG@3: 0.8176 NDCG@5: 0.8154 NDCG@10: 0.8540 MAE: 0.8266 MRSE: 1.0684"

Since all random seeds are set to 1234, I am wondering whether there are some tricks I haven't noticed.

Besides, for hyper-parameters, what is the difference between "Sample Size F" and "truncation length Ct"?

Looking forward to your response!
Bests,
Dongsheng

**Comment by echo740** [comment]
Dear Dongsheng,

Thanks for your following up. The previous code version is not what we finally used. I have updated the repository and you will find the new code files as well as the dataset used in our experiment. You can reproduce the results in our paper with the instructions. 

The sample size F means we sample F neighbored users for each user for graph convolution operation, and the truncation length Ct means that we truncate the recent Ct clicked items for one user as well as the recent Ct clicking users for one item as the history sequences in order to calculate the dynamic preference and attribute, respectively.

**Comment by flyingdoog** [comment]
Dear authors,
thanks a lot for your response. 

I have read the updated version. I still have some problems.
1) a small bug:  in train.py line 75 "mrse"-> "rmse"

2) I found in the function "get_metric()", you only keep test samples, whose user id appears over 10 in the test-set. The number is 65606 out of 132965, less than 50%.  Is this strategy commonly used in the social recommendation? is this strategy also applied to other baselines?

3) Since I am still training the model. I used your checkpoint file and remove this condition (use all test sample) and the results are "Test_loss: 1.1477 P@3: 0.5891 P@5: 0.4514 P@10: 0.2849 NDCG@3: 0.9281 NDCG@5: 0.9408 NDCG@10: 0.9524 MAE: 0.7948 RMSE: 1.0509". I think this result is very similar to a simple baseline: concatenating user and item embedding and using MLP to predict rating, which results are about 0.8 and 1.047). 

4) Since I have tried different methods on this dataset and I found that the user-user network provides very limited information. The conclusion is opposite to recent works.  Thus, I think I overlooked something important or my methods are not effective to use the social network. Sorry to bother you.

Looking forward to your response!
Dongsheng
