### ISSUE TITLE
Bug report and evaluation 

### ISSUE THREAD

**Issue by flyingdoog** [echo740/DANSER-WWW-19#5]
Dear authors,
thanks a lot for your response. 

I have read the updated version. I still have some problems.
1) a small bug:  in train.py line 75 "mrse"-> "rmse"

2) I found in the function "get_metric()", you only keep test samples, whose user id appears over 10 in the test-set. The number is 65606 out of 132965, less than 50%.  Is this strategy commonly used in the social recommendation? is this strategy also applied to other baselines?

3) Since I am still training the model. I used your checkpoint file and remove this condition (use all test sample) and the results are "Test_loss: 1.1477 P@3: 0.5891 P@5: 0.4514 P@10: 0.2849 NDCG@3: 0.9281 NDCG@5: 0.9408 NDCG@10: 0.9524 MAE: 0.7948 RMSE: 1.0509". I think this result is very similar to a simple baseline: concatenating user and item embedding and using MLP to predict rating, which results are about 0.8 and 1.047). 

4) Since I have tried different methods on this dataset and I found that the user-user network provides very limited information. The conclusion is opposite to recent works.  Thus, I think I overlooked something important or my methods are not effective to use the social network. Sorry to bother you.

Looking forward to your response!
Dongsheng

_Originally posted by @flyingdoog in https://github.com/echo740/DANSER-WWW-19/issues/4#issuecomment-516684068_

**Comment by echo740** [comment]
Hi Dongsheng,

Here is a response:

1、the filtering operation is also used for other baseline methods, so the comparison is fair. The motivation of using this operation is to achieve the similar results of some baselines according to their papers, although at last the results are still a little different. Since they did not release their codes, we have no idea how they implement the data preprocessing.

2、Directly using MLP-based collaborative filtering is actually a powerful baseline in this dataset as in our previous experiments. I think it is partly because in this dataset, the user network information does not provide much useful information. Based on this fact, other previous models that relies on matrix factorization of user network or adding constraints on similarity between two friends' embedding would over-use such social information and lead to a poor performance. In this sense, the attention-based methods would be more useful to filter our the `useful‘ social information.

**Comment by flyingdoog** [comment]
Thanks a lot for your response!
